label: golang

ingress:
  name: golang-ingress
  path: /

deployment:
  name: golang-deployment
  image:
    name: wil42/playground
    version: v1

service:
  name: golang-service
  type: Cluster_IP
  port: 8888