apiVersion: apps/v1
kind: Deployment
metadata:
  name: p3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p3
  template:
    metadata:
      labels:
        app: p3
    spec:
      containers:
      - image: wil42/playground:v1
        name: wil42-playground
        ports:
        - containerPort: 8888
