apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42-playground
  template:
    metadata:
      labels:
        app: wil42-playground
    spec:
      containers:
      - image: wil42/playground:v2
        name: wil42-playground
        ports:
        - containerPort: 8888
