apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app.kubernetes.io/instance: p3
  name: main-ingress
  namespace: dev
spec:
  rules:
    - http: null
      paths:
        - backend:
            service:
              name: wil42-playground
              port:
                number: 7171
          path: /
          pathType: Prefix

